version: "3"

services:
  db:
    image: postgres:13
    container_name: ft_transcendence-db
    restart: on-failure
    ports:
      - 5434:5432
    networks:
      - ft_transcendence
    env_file:
      - ./backend/.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./backend
    image: ft_transcendence-backend
    container_name: ft_transcendence-backend
    restart: on-failure
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - ft_transcendence
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl", "-fkLs", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    image: ft_transcendence-frontend
    container_name: ft_transcendence-frontend
    restart: on-failure
    ports:
      - 5000:5000
    networks:
      - ft_transcendence
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl", "-fkLs", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ft_transcendence:
    driver: bridge
    name: ft_transcendence
