version: "3"

services:
  db:
    image: postgres:13
    container_name: ft_transcendence-db
    restart: on-failure
    ports:
      - 5434:5432
    networks:
      - ft_transcendence
    env_file:
      - ./backend/.env
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m

  backend:
    build: ./backend
    image: ft_transcendence-backend
    container_name: ft_transcendence-backend
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - ft_transcendence
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -fLs http://localhost:3000/ > /dev/null
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

  frontend:
    build: ./frontend
    image: ft_transcendence-frontend
    container_name: ft_transcendence-frontend
    restart: on-failure
    ports:
      - 5000:5000
    networks:
      - ft_transcendence
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: curl -fLs http://localhost:5000/ > /dev/null
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m

networks:
  ft_transcendence:
    driver: bridge
    name: ft_transcendence
